#!/usr/bin/env python3
"""Generate installable skill distributions and the chat context pack."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
expected = {}
for src in sorted((root / 'workflow/skills').rglob('*')):
    if src.is_file():
        for dest in ['.agents/skills', '.claude/skills', 'templates/.agents/skills', 'templates/.claude/skills']:
            expected[root / dest / src.relative_to(root / 'workflow/skills')] = src.read_bytes()
pack = ['# Vibe Workflow chat context pack\n\nGenerated by scripts/sync-skills.py. Use with your PRD and Tech Design.\n\nThese are templates to fill, not evidence that setup or behavior has been checked.\n']
for src in [root / 'templates' / n for n in ['AGENTS.md', 'MEMORY.md', 'REVIEW-CHECKLIST.md']] + sorted((root / 'templates/agent_docs').glob('*.md')):
    pack.append('\n## File: ' + str(src.relative_to(root / 'templates')) + '\n\n' + src.read_text())
expected[root / 'docs/context-pack.md'] = '\n'.join(pack).encode()
errors = []
for path, content in expected.items():
    if args.check:
        if not path.exists() or path.read_bytes() != content:
            errors.append(str(path.relative_to(root)))
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
for dest in ['.agents/skills', '.claude/skills', 'templates/.agents/skills', 'templates/.claude/skills']:
    for path in (root / dest).rglob('*'):
        if path.is_file() and path not in expected:
            errors.append('Unexpected distribution file: ' + str(path.relative_to(root)))
if errors:
    raise SystemExit('Skill distributions out of sync:\n' + '\n'.join(errors))
print('Skill distributions and context pack ' + ('checked' if args.check else 'generated'))
